### ISSUE TITLE
Implement GitHub Pages

### ISSUE THREAD

**Issue by rg12301** [pulkitgovrani/One-Html-Page-Site#4]
Hi Pulkit 😊,

**I would suggest you to use [Github Pages](https://pages.github.com/).**
Since you have made a static website, it can be easily hosted on GitHub by implementing that.
And visitors can easily view your work (if you wish) without cloning and forking that on their side.

Cheers🤝,
rG

**Comment by pulkitgovrani** [comment]
Thanks for the suggestion buddy.
